-- MySQL Script generated by MySQL Workbench
-- Fri 18 Dec 2015 03:09:18 PM CET
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema jee-database
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `jee-database` ;

-- -----------------------------------------------------
-- Schema jee-database
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `jee-database` DEFAULT CHARACTER SET utf8 ;
USE `jee-database` ;

-- -----------------------------------------------------
-- Table `jee-database`.`Addresses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jee-database`.`Addresses` (
  `id` INT NOT NULL,
  `street` VARCHAR(45) NULL,
  `number` VARCHAR(45) NULL,
  `npa` VARCHAR(45) NULL,
  `town` VARCHAR(45) NULL,
  `country` VARCHAR(45) NULL,
  `distric` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `jee-database`.`Stocks`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jee-database`.`Stocks` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `localisation` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Stocks_Addresses1_idx` (`localisation` ASC),
  CONSTRAINT `fk_Stocks_Addresses1`
    FOREIGN KEY (`localisation`)
    REFERENCES `jee-database`.`Addresses` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `jee-database`.`Productors`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jee-database`.`Productors` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `headquarters` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Productors_Addresses1_idx` (`headquarters` ASC),
  CONSTRAINT `fk_Productors_Addresses1`
    FOREIGN KEY (`headquarters`)
    REFERENCES `jee-database`.`Addresses` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `jee-database`.`Productors_has_Stocks`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jee-database`.`Productors_has_Stocks` (
  `Productors_id` INT NOT NULL,
  `Stocks_id` INT NOT NULL,
  `bananakilo` INT NULL,
  PRIMARY KEY (`Productors_id`, `Stocks_id`),
  INDEX `fk_Productors_has_Stocks_Stocks1_idx` (`Stocks_id` ASC),
  INDEX `fk_Productors_has_Stocks_Productors1_idx` (`Productors_id` ASC),
  CONSTRAINT `fk_Productors_has_Stocks_Productors1`
    FOREIGN KEY (`Productors_id`)
    REFERENCES `jee-database`.`Productors` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Productors_has_Stocks_Stocks1`
    FOREIGN KEY (`Stocks_id`)
    REFERENCES `jee-database`.`Stocks` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
