-- MySQL Script generated by MySQL Workbench
-- Fri 11 Mar 2016 02:31:36 PM CET
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema jee-database
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `jee-database` ;

-- -----------------------------------------------------
-- Schema jee-database
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `jee-database` DEFAULT CHARACTER SET utf8 ;
USE `jee-database` ;

-- -----------------------------------------------------
-- Table `jee-database`.`Address`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jee-database`.`Address` (
  `id` INT NOT NULL,
  `street` VARCHAR(45) NULL,
  `number` VARCHAR(45) NULL,
  `npa` VARCHAR(45) NULL,
  `town` VARCHAR(45) NULL,
  `country` VARCHAR(45) NULL,
  `distric` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `jee-database`.`Banana_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jee-database`.`Banana_type` (
  `id` INT NOT NULL,
  `label` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `jee-database`.`Package`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jee-database`.`Package` (
  `id` INT NOT NULL,
  `gatherdate` DATE NULL,
  `productor` INT NOT NULL,
  `hangar` INT NOT NULL,
  `client` INT NOT NULL,
  `is_transit` TINYINT(1) NOT NULL,
  `Banana_type_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Package_Banana_type1_idx` (`Banana_type_id` ASC),
  CONSTRAINT `fk_Package_Banana_type1`
    FOREIGN KEY (`Banana_type_id`)
    REFERENCES `jee-database`.`Banana_type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `jee-database`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jee-database`.`User` (
  `id` INT NOT NULL,
  `Address_id` INT NOT NULL,
  `password` TEXT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_User_Address1_idx` (`Address_id` ASC),
  CONSTRAINT `fk_User_Address1`
    FOREIGN KEY (`Address_id`)
    REFERENCES `jee-database`.`Address` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `jee-database`.`Stock`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jee-database`.`Stock` (
  `id` INT NOT NULL,
  `label` VARCHAR(45) NULL,
  `capacity_max` INT NULL,
  `capacity_current` INT NULL,
  `Address_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Stock_Address1_idx` (`Address_id` ASC),
  CONSTRAINT `fk_Stock_Address1`
    FOREIGN KEY (`Address_id`)
    REFERENCES `jee-database`.`Address` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `jee-database`.`Role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jee-database`.`Role` (
  `id` INT NOT NULL,
  `label` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `jee-database`.`User_has_Role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jee-database`.`User_has_Role` (
  `Role_id` INT NOT NULL,
  `User_id` INT NOT NULL,
  PRIMARY KEY (`Role_id`, `User_id`),
  INDEX `fk_User_has_Role_Role1_idx` (`Role_id` ASC),
  INDEX `fk_User_has_Role_User1_idx` (`User_id` ASC),
  CONSTRAINT `fk_User_has_Role_User1`
    FOREIGN KEY (`User_id`)
    REFERENCES `jee-database`.`User` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_User_has_Role_Role1`
    FOREIGN KEY (`Role_id`)
    REFERENCES `jee-database`.`Role` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `jee-database`.`Command`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jee-database`.`Command` (
  `id` INT NOT NULL,
  `date_order` DATE NULL,
  `date_payement` DATE NULL,
  `User_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Command_User1_idx` (`User_id` ASC),
  CONSTRAINT `fk_Command_User1`
    FOREIGN KEY (`User_id`)
    REFERENCES `jee-database`.`User` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `jee-database`.`Command_has_Package`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jee-database`.`Command_has_Package` (
  `Command_id` INT NOT NULL,
  `Package_id` INT NOT NULL,
  PRIMARY KEY (`Command_id`, `Package_id`),
  INDEX `fk_Command_has_Package_Package1_idx` (`Package_id` ASC),
  INDEX `fk_Command_has_Package_Command1_idx` (`Command_id` ASC),
  CONSTRAINT `fk_Command_has_Package_Command1`
    FOREIGN KEY (`Command_id`)
    REFERENCES `jee-database`.`Command` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Command_has_Package_Package1`
    FOREIGN KEY (`Package_id`)
    REFERENCES `jee-database`.`Package` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `jee-database`.`User_has_Stock`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jee-database`.`User_has_Stock` (
  `User_id` INT NOT NULL,
  `Stock_id` INT NOT NULL,
  PRIMARY KEY (`User_id`, `Stock_id`),
  INDEX `fk_User_has_Stock_Stock1_idx` (`Stock_id` ASC),
  INDEX `fk_User_has_Stock_User1_idx` (`User_id` ASC),
  CONSTRAINT `fk_User_has_Stock_User1`
    FOREIGN KEY (`User_id`)
    REFERENCES `jee-database`.`User` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_User_has_Stock_Stock1`
    FOREIGN KEY (`Stock_id`)
    REFERENCES `jee-database`.`Stock` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `jee-database`.`Package_has_Stock`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jee-database`.`Package_has_Stock` (
  `Package_id` INT NOT NULL,
  `Stock_id` INT NOT NULL,
  PRIMARY KEY (`Package_id`, `Stock_id`),
  INDEX `fk_Package_has_Stock_Stock1_idx` (`Stock_id` ASC),
  INDEX `fk_Package_has_Stock_Package1_idx` (`Package_id` ASC),
  CONSTRAINT `fk_Package_has_Stock_Package1`
    FOREIGN KEY (`Package_id`)
    REFERENCES `jee-database`.`Package` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Package_has_Stock_Stock1`
    FOREIGN KEY (`Stock_id`)
    REFERENCES `jee-database`.`Stock` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
