-- MySQL Script generated by MySQL Workbench
-- Fri 15 Jan 2016 03:48:30 PM CET
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema jee-database
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `jee-database` ;

-- -----------------------------------------------------
-- Schema jee-database
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `jee-database` DEFAULT CHARACTER SET utf8 ;
USE `jee-database` ;

-- -----------------------------------------------------
-- Table `jee-database`.`Addresses`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `jee-database`.`Addresses` ;

CREATE TABLE IF NOT EXISTS `jee-database`.`Addresses` (
  `id` INT NOT NULL,
  `street` VARCHAR(45) NULL,
  `number` VARCHAR(45) NULL,
  `npa` VARCHAR(45) NULL,
  `town` VARCHAR(45) NULL,
  `country` VARCHAR(45) NULL,
  `distric` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `jee-database`.`Hangar`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `jee-database`.`Hangar` ;

CREATE TABLE IF NOT EXISTS `jee-database`.`Hangar` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `localisation` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Stocks_Addresses1_idx` (`localisation` ASC),
  CONSTRAINT `fk_Stocks_Addresses1`
    FOREIGN KEY (`localisation`)
    REFERENCES `jee-database`.`Addresses` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `jee-database`.`Productors`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `jee-database`.`Productors` ;

CREATE TABLE IF NOT EXISTS `jee-database`.`Productors` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `headquarters` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Productors_Addresses1_idx` (`headquarters` ASC),
  CONSTRAINT `fk_Productors_Addresses1`
    FOREIGN KEY (`headquarters`)
    REFERENCES `jee-database`.`Addresses` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `jee-database`.`Productors_has_Stocks`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `jee-database`.`Productors_has_Stocks` ;

CREATE TABLE IF NOT EXISTS `jee-database`.`Productors_has_Stocks` (
  `Productors_id` INT NOT NULL,
  `Stocks_id` INT NOT NULL,
  `bananakilo` INT NULL,
  PRIMARY KEY (`Productors_id`, `Stocks_id`),
  INDEX `fk_Productors_has_Stocks_Stocks1_idx` (`Stocks_id` ASC),
  INDEX `fk_Productors_has_Stocks_Productors1_idx` (`Productors_id` ASC),
  CONSTRAINT `fk_Productors_has_Stocks_Productors1`
    FOREIGN KEY (`Productors_id`)
    REFERENCES `jee-database`.`Productors` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Productors_has_Stocks_Stocks1`
    FOREIGN KEY (`Stocks_id`)
    REFERENCES `jee-database`.`Hangar` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `jee-database`.`Client`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `jee-database`.`Client` ;

CREATE TABLE IF NOT EXISTS `jee-database`.`Client` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `adresse` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Client_Addresses1_idx` (`adresse` ASC),
  CONSTRAINT `fk_Client_Addresses1`
    FOREIGN KEY (`adresse`)
    REFERENCES `jee-database`.`Addresses` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `jee-database`.`Package`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `jee-database`.`Package` ;

CREATE TABLE IF NOT EXISTS `jee-database`.`Package` (
  `id` INT NOT NULL,
  `bananakilo` VARCHAR(45) NULL,
  `bananatype` VARCHAR(45) NULL,
  `gatherdate` DATE NULL,
  `productor` INT NOT NULL,
  `localisation` INT NOT NULL,
  `client` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Package_Productors1_idx` (`productor` ASC),
  INDEX `fk_Package_Client1_idx` (`client` ASC),
  INDEX `fk_Package_Stocks1_idx` (`localisation` ASC),
  CONSTRAINT `fk_Package_Productors1`
    FOREIGN KEY (`productor`)
    REFERENCES `jee-database`.`Productors` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Package_Client1`
    FOREIGN KEY (`client`)
    REFERENCES `jee-database`.`Client` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Package_Stocks1`
    FOREIGN KEY (`localisation`)
    REFERENCES `jee-database`.`Hangar` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
